version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      nest-and-prisma:
        patterns:
          - '@nestjs/*'
          - '@prisma/*'
          - 'prisma'
      dev-tools:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
